/**
 * Advisor Quotes
 * Répliques de Michael Harper, le critique (fictif) du Movie Advisor. Une est
 * tirée au sort à chaque ouverture de l'écran — c'est purement décoratif.
 *
 * Ton visé : le critique de télé des années 90, sûr de lui et un peu cabot.
 * Court obligatoire : le panneau fait ~21 caractères de large sur ~10 lignes.
 */

export const QUOTES = [
  'I watch so you don\'t have to.',
  'Trust me. I have seen everything.',
  'Popcorn optional. Taste mandatory.',
  'I was right about that one. Again.',
  'Two thumbs. Both mine.',
  'They don\'t make them like this. Literally.',
  'I have opinions. Many opinions.',
  'The projector never lies.',
  'I gave it four stars. Under protest.',
  'Cinema is not dead. It is just napping.',
  'I have seen worse. Not much worse.',
  'This one holds up. Mostly.',
  'A masterpiece. Or close enough.',
  'I fell asleep. That is a review.',
  'Great films age. Bad films just get old.',
  'I do not review. I forgive.',
  'Subtitles build character.',
  'Black and white is a colour.',
  'The director knew. He simply did not care.',
  'Every frame a painting. Some abstract.',
  'I laughed. I cried. I checked my watch.',
  'Runtime is a promise, not a threat.',
  'The book was different. Not better.',
  'I have never walked out. Only left early.',
  'A sequel nobody asked for. I asked.',
  'Style over substance is still style.',
  'They filmed this on purpose.',
  'The score does the heavy lifting.',
  'Practical effects age like wine.',
  'I remember the ending. That is rare.',
  'Slow is not the same as boring.',
  'Loud is not the same as exciting.',
  'This aged like milk. Good milk.',
  'The critics were wrong. I was there.',
  'Underrated. By everyone but me.',
  'Overrated. Say it louder.',
  'A cult classic in waiting.',
  'The twist works. The first time.',
  'I own this on three formats.',
  'Widescreen or nothing.',
  'The trailer spoiled it. Watch anyway.',
  'Not for everyone. Perfect for someone.',
  'A flawed gem is still a gem.',
  'Ambitious. Which is half the battle.',
  'Nobody makes a clean 92 minutes anymore.',
  'The lighting is the whole plot.',
  'That performance deserved better.',
  'A cast this good is a small miracle.',
  'The edit saved it. Barely.',
  'Straight to video. Straight to my heart.',
  'A B-movie with an A-movie soul.',
  'Low budget. High ideas.',
  'Big budget. Small ideas.',
  'They spent it all on the first act.',
  'The third act forgives the second.',
  'I would watch this again. Reluctantly.',
  'Bring a blanket. And patience.',
  'Watch it late. It plays better.',
  'This one needs a rewatch. Or three.',
  'The sound design does the acting.',
  'A quiet film in a loud decade.',
  'Nobody understood it. Including me.',
  'Weird on purpose. My favourite kind.',
  'Genre is a suggestion.',
  'The rules were made to be broken. Gently.',
  'A love letter to nothing in particular.',
  'The camera moves. So should you.',
  'They shot it in 30 days. It shows. Nicely.',
  'Stunts real. Stakes realer.',
  'The villain steals it. As usual.',
  'A hero is only as good as the fall.',
  'The ending earns itself.',
  'No spoilers. Only warnings.',
  'I do not do star ratings. Here are four.',
  'Second viewing. Different film.',
  'It has a face only a critic could love.',
  'Bold. Which is to say strange.',
  'The pacing is a choice. A brave one.',
  'Three hours well spent. Roughly.',
  'Ninety minutes. Not one wasted.',
  'Under two hours. A gentleman\'s runtime.',
  'It knows exactly what it is.',
  'A crowd-pleaser with a mean streak.',
  'Funny until it is not. That is the trick.',
  'Sad in the good way.',
  'Scary in the cheap way. Still works.',
  'I jumped. Do not tell anyone.',
  'The monster is better unseen.',
  'The dog lives. You are welcome.',
  'Nobody says the title. Refreshing.',
  'The opening shot sells the whole thing.',
  'It peaks early. Then peaks again.',
  'Miscast. Magnificently.',
  'A director at the top of their game.',
  'A director figuring it out. On camera.',
  'The remake is fine. This is better.',
  'The original had less money. And more nerve.',
  'A franchise before that was a word.',
  'They ran out of film. Not ideas.',
  'One take. One legend.',
  'Made for nobody. Adored by many.',
  'Ahead of its time. Behind on plot.',
  'A perfect film. Do not @ me.',
  'Good taste is just my taste.',
  'Disagree. You will be wrong.',
  'Watch it. Then argue with me.',
];

export default QUOTES;
